### ISSUE TITLE
最新版代码下如何写二叉树可视化？

### ISSUE THREAD

**Issue by liuliqianxiao** [phenomLi/Blog#43]
现有的二叉树可视化教程好像与最新版代码不匹配了，求更新

**Comment by phenomLi** [comment]
抱歉，由于个人原因，好久没上github了！如果你需要使用可视化库可以邮件联系我，我随时回复，这个issue需要关闭了。

**Comment by phenomLi** [comment]
> 现有的二叉树可视化教程好像与最新版代码不匹配了，求更新

抱歉，由于个人原因，好久没上github了！如果你需要使用可视化库可以邮件联系我，我随时回复，这个issue需要关闭了。
